spring:
  application:
    name: mail_send_demo1
    mail:
      host: smtp.qq.com
      username: 2863039606@qq.com
      password: nmypwpdgufigdghb
      default-encoding: UTF-8
      properties.mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      # 打印邮件发送过程，生产环境关闭
      properties.mail.debug: true

server:
  port: 8080

email:
  smtp:
    host: smtp.qq.com
    email: 2863039606@qq.com
    name: 邮件提醒系统
    password: nmypwpdgufigdghb
    port: 25